server.port=7001

#DB Configurations
db_server=localhost
db_port=3306
db_name=waarc
db_user=root
db_password=f1ps

#The initial number of connections that are created when the pool is started.Default 0
db_pool_initial_size=5
#The maximum number of active connections that can be allocated from this pool at the same time. Default 8
db_pool_max_size=20
#The maximum number of connections that can remain idle in the pool, without extra ones being released. Default 8
db_pool_max_idle_size=5
#The minimum number of connections that can remain idle in the pool, without extra ones being created. Default 0
db_pool_min_idle_size=2
#The maximum number of milliseconds that the pool will wait (when there are no available connections) for a connection to be returned before throwing an exception
#max_wait in milliseconds (keep 9 sec wait time) Default value indefinite.
db_pool_max_wait=9000
#Timeout in seconds before an abandoned connection can be removed. Default is 300 seconds
db_pool_remove_abandoned_timeout=180
#Remove abandoned connections if they exceed removeAbandonedTimeout. Default false
db_pool_remove_abandoned_on_borrow=true
#Removes abandoned connections on the maintenance cycle (when eviction ends). Default false
db_pool_remove_abandoned_on_maintenance=true
#60000 millisec (60 sec). Default is -1 ( no idle object evictor thread will be run).
db_pool_time_between_eviction_runs_millis=60000


# --- Gmail SMTP Configuration ---
mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.smtp.auth=true
mail.smtp.starttls.enable=true

# --- Your Gmail account ---
mail.username=sachinseengh@gmail.com
mail.password=fxncozbtyhwdcldq

Admin_Email=sachinseengh@gmail.com
Admin_Name=sachin
Admin_Password=sachin

